### ISSUE TITLE
MintUpdate 5.2.9: Missing partially package information

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/mintupdate#256] opened 2017-06-28 21:16 UTC
Mint 18.2 beta Cinnamon 64 bit
MintUpdate 5.2.9

For all packages, where the name starts with "mint" (currently mint-artwork-mate until mint-y-theme) there appear no information about the affected packages in the description.

I have a special test system, where I never applied any updates except the update manager itself (for testing its behavior). So I see there all updates, which got until today available. The described problem does only exist for the mint* updates, no other updates are affected (also not the x-apps).

**Comment by clefebvre** [comment] 2017-06-29 10:17
Please elaborate on:

> no information about the affected packages in the description

**Comment by Cos-mo** [comment] 2017-06-29 10:45
Usually you have in the description pane of the marked package at the bottom the information, which packages are really affected by the update. E. g. for pix it says: 2 packages: pix pix-data. For all (without exception) updates, which start with "mint" in the name (currently 8 updates), this line does not appear at all. There is in the description section the short description, what this update / package does, and nothing more.

I wondered also, if the missing listing of packages could have the reason, that there is only one package for this update? But this can also not be, because I see for example the update libarchive, where also only one package is affected by the update and in this case I see the affected package named at the bottom f the description.

**Comment by Pjotr123** [comment] 2017-06-29 11:11
I can't reproduce the problem (Virtual Machine with Mint Mate 18.2, Update Manager 5.2.9):

https://postimg.org/image/uyh0mfrrj/

and:
https://postimg.org/image/6v5jtr0l3/

All looks well, as it should...

Apparently the number of packages is only shown when more than one package is involved. See xviewer (which also has no package listing).

This seems to be deliberate design: there's no use in mentioning the number of packages when only one package is involved, because the package name is already in the update pane.

**Comment by clefebvre** [comment] 2017-06-29 11:28
Hi,

It's by design. The info is shown when the list of package names differs from the update name.

It might be better to make this information more consistent by showing the list of packages no matter what.

In any case, I'll close this issue as this isn't a bug.

**Closed by clefebvre** 2017-06-29 11:28 UTC

**Comment by Cos-mo** [comment] 2017-06-29 11:56
I confirm, that the issue is closed. Only an hour ago there came the idea in my mind, that the difference between package name and the update name makes possibly the difference (but at that time it was only a guess). For my supporting task it is good to know, that the current behavior is by design, for the future the announced change would surely be an enhancement, but this is absolutely not important or time-critical.
