### ISSUE TITLE
Stuck on corrupted cache on Mint 18.3

### ISSUE THREAD

**Issue by kofalt** [linuxmint/mintupdate#363] opened 2018-06-15 18:15 UTC
A spiritual successor to #284.

I received the "Your APT cache is corrupted" error, clicked "OK" to open the Software Sources menu, chose different mirrors for both Main and Base, and clicked the update button. No obvious problems occurred, but when going back to the main window and clicking Refresh, I'm stuck at the same state.

I also tried using the "Fix mergelist problems" and "Purge residual configuration" of the Maintenance section as suggested by [this forum comment](https://www.reddit.com/r/linuxmint/comments/63g2x8/apt_cache_corrupted/dfu6t86), as well as attempting to rectify the problem manually with [this script](https://gist.github.com/kumichou/fbbac1fcba896a797116).

[This thread](https://forums.linuxmint.com/viewtopic.php?t=213574) had a workaround that works for me for the moment: launching `mintupdate` manually from a root shell results in no problems.

---

![image](https://user-images.githubusercontent.com/265071/41483155-9bfd596a-709d-11e8-8076-bb5ae43b276b.png)

![image](https://user-images.githubusercontent.com/265071/41483142-8bc79b00-709d-11e8-96ed-ef50da02face.png)

**Comment by clefebvre** [comment] 2018-06-19 17:46
What does "apt policy" say?

**Comment by kofalt** [comment] 2018-06-21 20:24
An update: it looks like the root of the problem was a command I ran to install nvidia CUDA packages, which added a file to /etc/apt that was not world-readable. A chmod fixed the problem.

Would it be possible to communicate that error to the user? Or alternatively, tell me to be more careful & close the ticket :)

**Comment by clefebvre** [comment] 2018-06-29 10:08
Thanks @kofalt we'll try to reproduce to see if we can improve the error reporting.

**Comment by DJCrashdummy** [comment] 2018-11-04 22:38
i ran into the same error, which was driving me nuts...
`synaptic`, `aptitude` and `apt` was still working fine, but `gdebi-gtk` also threw me an error which was really confusing.

after fiddling around i have an idea why:
i set UMASK on the system to 027 - to maximize the privacy on a multiuser-system. and now every time after changing the mirrors via `mintsources` the `/etc/apt/sources.list.d/official-package-repositories.list` gets set from 644 to 640 and in `mintupdate` this misleading error message appears.

not sure if the underlying bug is worth a separate issue; if so, tell me... but i guess it is one for the `mintsources`-repo?

**Comment by DJCrashdummy** [comment] 2018-11-04 23:20
wouldn't be the solution to simply check the permissions of all `sources.list` and show an appropriate message if they are not readable by `mintupdate`.
since funny wise in my case _"switching to another mirror"_ is not the solution for this error, but the cause! :stuck_out_tongue:

**Comment by xenopeek** [comment] 2018-11-05 17:46
@DJCrashdummy: as noted on https://github.com/linuxmint/mintsources/issues/97#issuecomment-435964562, I can't reproduce the issue with the steps you provided. The cause of your issue isn't umask and must be something else you haven't narrowed down on yet. You can ask for help on the forums with troubleshooting to find the cause. See our [troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/).

To be clear, if I manually set `/etc/apt/sources.list.d/official-package-repositories.lis` to permissions 0640 I get the "Your APT cache is corrupted" error in mintupdate as per this issue (both on Linux Mint 18.3 and 19). But your steps to reproduce that file getting permissions 0640 don't work in my testing and in fact changing a mirror resets the file's permissions to 0644.

**Comment by gm10** [comment] 2019-03-07 20:04
This is too particular and out there of a problem for mintupdate to test for specifically in my opinion. That said, the referenced pull request, which will close this, addresses it insofar as it writes potential warning messages to the log. In a case like the present you would find something like this in the log:

`APT policy error:
W: Unable to read /etc/apt/sources.list.d/official-package-repositories.list - open (13: Permission denied)`

Note that such a warning message only leads to an error in mintupdate itself when it affects the official repositories list. If the problem is with other lists, we don't really care, but the patch will at least give you that information in the log now.

**Comment by gm10** [comment] 2019-03-08 09:55
Update: @clefebvre convinced me to show the error message also in the main window, so now it will be (if the error about the official repositories missing was triggered, too, otherwise, as explained before, you'll still find it in the log though).

**Closed** 2019-03-12 16:45 UTC
Labels: In Progress
