### ISSUE TITLE
'Checking for updates' (python checkAPT.py) almost hangs PC for minutes

### ISSUE THREAD

**Issue by EndeavourAccuracy** [linuxmint/mintupdate#51] opened 2014-07-19 18:23 UTC
Every time the 'Checking for updates' process (python checkAPT.py) runs, it almost hangs my PC for about two minutes. The hard disk is going crazy and during this period selecting windows or basically doing /anything/ is impossible. I was forced to change the Auto-Refresh to 1 day, but even that is just too painful to endure. So I've quit the Update Manager entirely and I'm now doing apt-get update/upgrade by hand.

**Comment by Braza** [comment] 2015-01-22 12:55
same here man. Mint 17

**Comment by helaughsatfear** [comment] 2015-07-02 02:32
Same here on 17.1
"iotop" said checkAPT.py was using 99.9% IO
Had to sudo KILL -STOP XXXX

**Comment by pdelre** [comment] 2015-08-12 19:03
I've had the same issues in many of the versions (17, 17.1, 17.2), but I always assumed it was because I was running Linux Mint in VirtualBox (Windows Host).

**Comment by clefebvre** [comment] 2015-10-28 14:46
Can you run checkAPT.py on its own and see if that causes 100% CPU?

sudo /usr/lib/linuxmint/mintUpdate/checkAPT.py 2>/dev/null

And also without sudo:

/usr/lib/linuxmint/mintUpdate/checkAPT.py 2>/dev/null

**Comment by Stefan-Code** [comment] 2015-11-18 22:45
@clefebvre I am also experiencing this problem. When calling it directly, it also causes 100% CPU but only for ~2 seconds.
When running with `sudo` I see `usr/lib/apt/methods/copy` causing a lot of CPU load.

**Comment by antoine-lizee** [comment] 2015-12-08 08:44
I myself thought my box got crazy. It's a big server (12 cores, 64GB RAM) but the IO was blocking me from doing anything. It lasted around 30 min, and right till the end I could see a glimpse of a few `checkAPT.py` from a `top` that finally got through. 

Would be happy to do some digging in (looked at syslog, seems that there was quite a few oom-killer calls.

**Comment by bretthartshorn** [comment] 2015-12-10 00:13
i'm running 17.2 and just noticed this to, its slowing down my whole machine.

**Comment by EduardDopler** [comment] 2015-12-10 10:42
As it reads the APT cache, we can consider 100% CPU load normal behavior. But only for some seconds.
Though checkAPT.py could be optmized at some points, I don't see anything causing hangs. There might be regressions in the Python APT module.

Could someone do more debugging? Do you always experience these issues or only in some situations like when updates are available?

Do the apt commands in python fail, too? You can check that by running `sudo python2` and entering:
```python
import apt
cache = apt.Cache()  # normal: high CPU for some seconds
cache.update()       # normal: high network for many seconds
cache.upgrade(False)
changes = cache.get_changes()
print "Changes:", len(changes)
cache.upgrade(True)
changes = cache.get_changes()
print "Changes (dist_upgrade):", len(changes)
```

**Comment by Stefan-Code** [comment] 2015-12-10 10:50
When running that manually, everything seems to be ok.
`cache = apt.Cache()`: ~ 2 seconds
```python
#upgrade
>>> len(changes)
124
```
and
```python
#dist upgrade
len(changes)
129
```
Can't comment on when this is occurring, only had it happen once.

**Comment by bretthartshorn** [comment] 2015-12-12 03:24
it is happening to me like every 15minutes, and on a slow netbook, it fully locks up my system for a few seconds, which is super annoying.  I didn't have this problem until recently, not sure if i updated some packages that caused this problem.

**Comment by EduardDopler** [comment] 2015-12-12 08:54
@bretthartshorn Could you run the code I posted?

**Comment by antoine-lizee** [comment] 2015-12-17 11:26
Rq: This is the first time it ever happened to me (and I've been running LMDE for 3 years). Could be a SWAP issue? I had a lot of stuff going on. Sorry to not be more helpful, but I cannot reproduce.

**Comment by intracer** [comment] 2017-04-29 16:32
It just endlessly writes to the disk for unknown reason. killed it and system become responsive again

**Comment by xenopeek** [comment] 2018-01-25 20:43
Linux Mint 18.2 reworked the mintupdate backend. Closing.

**Closed by xenopeek** 2018-01-25 20:43 UTC
Labels: BUG

**Comment by xhdix** [comment] 2018-10-20 19:07
99% of disk usage

**Comment by cossio** [comment] 2018-10-22 14:51
@xenopeek Reopen?

**Comment by xenopeek** [comment] 2018-10-22 18:46
Hi, seeing as this is from 2014 while mintupdate has had a major overhaul for Linux Mint 18.2 I won't reopen this as its history would just confuse as to the actual cause. Please test this against the latest mintupdate version, go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and take help from the forums to analyze and hopefully solve the issue. If during troubleshooting others can reproduce the issue a new issue can be reported with this new information.

**Comment by halmai** [comment] 2019-04-06 11:54
I am having the same issue. The OS is Linux Mint 19 Tara. 

The laptop has 4GB RAM and swaps like a crazy. It is really annoying, if the script is running then the mouse doesn't move. If I can log in from a remote ssh then I kill something else (usually Firefox) and then it goes well again. 

Could this ticket be reopened, please?

**Comment by gm10** [comment] 2019-04-06 13:27
No. See comment above yours. 

Also if your system is out of memory there's nothing much that can be done from our end.

**Comment by user89907** [comment] 2019-08-29 18:10
I'm on Mint 18.1, just saw this happening.
Here's how to disable it, note this is not the prettiest solution,
as you disable this check.
However, you should still be able to run
apt-get update  and apt-get upgrade

To disable the check:
Start a terminal, become root, then:
> # locate checkAPT.py
> /usr/lib/linuxmint/mintUpdate/
> #  chmod -x /usr/lib/linuxmint/mintUpdate/checkAPT.py

Make a note somewhere about the change, I prefer to make a serverlog-MACHINENAME.txt
in each machine, keeping a log there which specifies on which date I changed
what stuff.
To reverse, when
