### ISSUE TITLE
Error message window truncates text and buttons

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mintupdate#589] opened 2019-11-24 18:03 UTC
**Describe the bug**
Error message window shows the beginning of the text off the top of the screen and shows buttons off the bottom of the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/47056543/69498851-39023600-0ee4-11ea-977a-b14b482a699a.png)

**To Reproduce**
Open the Manager any which way.
Refresh.
Abort via the cancel button.
Possibly one needs some or all of: HiDPI; a certain screen size; a certain length of error message; certain things to generate the error message in the first place.

**Expected behavior**
No truncation.

**Distribution:**
- [X] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)

**Software version:**
5.5.4.2

**Logs:**
11.24@02:12 ++ Launching Update Manager
11.24@02:12 ++ Initial refresh will happen in 0 day(s), 0 hour(s) and 10 minute(s)
11.24@02:12 ++ Starting refresh (local only)
11.24@02:12 ++ System is up to date
11.24@02:12 ++ Refresh finished
11.24@02:13 ++ Changes to the package cache detected, triggering refresh
11.24@02:13 ++ Starting refresh (local only)
11.24@02:13 ++ System is up to date
11.24@02:13 ++ Refresh finished
11.24@02:22 ++ Update Manager is in tray mode, performing initial refresh
11.24@02:22 ++ Starting refresh (retrieving lists of updates from remote servers)
11.24@02:22 ++ System is up to date
11.24@02:22 ++ Refresh finished
11.24@02:22 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 59 minute(s)
11.24@04:22 ++ Update Manager is in tray mode, performing recurring refresh
11.24@04:22 ++ Starting refresh (retrieving lists of updates from remote servers)
11.24@04:22 ++ System is up to date
11.24@04:22 ++ Refresh finished
11.24@04:22 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 59 minute(s)
11.24@17:49 ++ Starting refresh (retrieving lists of updates from remote servers)
11.24@17:50 ++ System is up to date
11.24@17:50 ++ Refresh finished
11.24@17:50 ++ Starting refresh (retrieving lists of updates from remote servers)
11.24@17:57 ++ System is up to date
11.24@17:57 ++ Refresh finished
11.24@17:57 ++ Starting refresh (retrieving lists of updates from remote servers)
11.24@18:01 ++ System is up to date
11.24@18:01 ++ Refresh finished

**Additional context**
I thought there was a bug report about the buttons already. I cannot find it.

**Locale:**
LANG=en_GB.UTF-8
LANGUAGE=en_GB
LC_CTYPE=en_GB.UTF-8
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=

**Comment by JosephMcc** [comment] 2019-11-25 16:00
This is a duplicate of an issue you already commented in: https://github.com/linuxmint/mintupdate/issues/368

**Closed by JosephMcc** 2019-11-25 16:00 UTC
Labels: BUG
