### ISSUE TITLE
[Bug] Update Manager thinks Vivaldi Web Browser is by Linux Mint

### ISSUE THREAD

**Issue by feren** [linuxmint/mintupdate#191] opened 2016-12-05 18:21 UTC
Pretty much what the title says, look at the origin column (BTW, I was Authenticating when I took the screenie):
![screenshot from 2016-12-05 18-14-50](https://cloud.githubusercontent.com/assets/11057934/20896862/a4d3a388-bb17-11e6-8041-54e46942ae7f.png)

**Comment by brennanhm** [comment] 2016-12-06 03:18
Hi,

This was a known issue when the [PR](https://github.com/linuxmint/mintupdate/pull/184) was submitted. The problem is that non-Launchpad PPAs don't provide a consistent 'origin' field, so the default ("Linux Mint") gets applied in checkAPT.py. My idea was to give Linux Mint packages an explicit origin, and rewrite checkAPT.py so that everything else gets a default label like "Third-party", or something to that effect. The other option is to remove the 'origin' portion and just leave the site URL that the package is being downloaded from.

**Comment by monsta** [comment] 2017-01-17 12:44
Yeah, same for VirtualBox from download.virtualbox.org repo.

**Comment by dg1727** [comment] 2017-02-10 18:04
I like brennanhm's first idea.  If the URL is also used, then for example:  

`deb http://mirrorservice.org/sites/ftp.debian.org/debian/ jessie-backports main contrib non-free`

might be shown like 

`mirrorservice.org/sites/ftp.debian.org/debian/ jessie-backports` (possibly with the space turned into a linebreak)
1.  Repository URLs don't have a consistent format, either, so almost all of the URL can be shown.  
2.  In this example, the `jessie-backports` isn't technically part of the URL, but is meaningful to the user.

**Comment by theel0ja** [comment] 2017-03-23 16:22
Fixed in https://github.com/linuxmint/mintupdate/commit/069972f69ecee473395e94d0914c0b07fa5e096f

**Closed** 2017-03-23 16:35 UTC
