### ISSUE TITLE
Translations for quantity

### ISSUE THREAD

**Issue by KOLEGA007** [linuxmint/mintupdate#72] opened 2014-10-15 19:58 UTC
My language have different versions of multiplying nouns
like 1
2,3,4
5 ... etc. In translations we have on variants 1 and 2+

This update contains 1 package: 
This update contains %d packages:

**Comment by clefebvre** [comment] 2015-10-28 14:53
Duplicate of https://github.com/linuxmint/mintupdate/issues/110

**Closed by clefebvre** 2015-10-28 14:53 UTC
