### ISSUE TITLE
Double launch needed at log in

### ISSUE THREAD

**Issue by alex1sc** [linuxmint/mintupdate#600] opened 2020-01-02 08:20 UTC
**Describe the bug**
I transfered admin rights "adm" to my Administrator's account. When I want to upgrade software with MintUpdate, I log on as administrator and I have to launch MintUpdate twice before being able to use it. The first time if I try to install update, it just collapse. Thus, I have to relauch it for being able to install updates. 

**Screenshots**
If applicable, add screenshots to help explain your problem, you can just drag & drop them here.

**To Reproduce**

**Expected behavior**

**Distribution:**
Host: EverXL Kernel: 4.15.0-72-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 
           Desktop: Cinnamon 4.2.4 wm: muffin dm: LightDM Distro: Linux Mint 19.2 Tina 
           base: Ubuntu 18.04 bionic 

**Software version:**
5.5.4.2

**Logs:**
Copy & paste the log output from Update Manager > View > Information here.

**Crash report:**
If you are reporting a crash, please run `mintupdate` from a terminal window, reproduce the crash and copy & paste any output from the terminal window here.

**Additional context**
Add any other context about the problem you think might be relevant.

**Locale:**
If the problem is with text not getting displayed correctly, paste the output of the terminal command `locale`.

**Comment by xenopeek** [comment] 2020-05-24 09:53
Duplicate of #604 

mintupdate is automatically started 20 seconds after you log in and when you start mintupdate manually before that, your mintupdate gets killed because each time mintupdate is started it kills any other running mintupdate. I assume that's the case for you. As a workaround you can disable Update Manager in Startup Applications for that account, to disable it starting automatically.

**Closed by xenopeek** 2020-05-24 09:53 UTC
