### ISSUE TITLE
mintupdate 4.8.1 may fail to ever query the repos on systems which are not up 24 * 7

### ISSUE THREAD

**Issue by KHeilen** [linuxmint/mintupdate#98] opened 2015-03-29 21:46 UTC
The old mintupdate (4.4.7 on Mint 13 e.g.) queries the Mint and Ubuntu repos on startup.
Only then mintupdate goes to sleep for the configured timeout before querying the repos again.
The current mintupdate 4.8.1 on Mint 17/17.1, however, only checks the local software list for unprocessed updates on startup.
Then it goes to sleep for the configured timeout before actually querying the Mint and Ubuntu repos for the first time.
In cases where the uptime of a computer is shorter than the configured mintUpdate timeout this will prevent mintUpdate from ever querying the repos.
Cf. this Linux Mint forum thread, please: [Problem with Mint updater scheduler ?](http://forums.linuxmint.com/viewtopic.php?f=47&t=192325)
Conclusion:
Future releases of mintupdate should query the repos on startup again and only then go to sleep for the configured timeout.

**Comment by darealshinji** [comment] 2015-04-01 05:42
What about adding an option to automatically check on startup? People who don't like that could deactivate it.

**Comment by KHeilen** [comment] 2015-04-01 21:33
Sure, making the behaviour configurable would be all right.

**Comment by wintertroubles** [comment] 2015-04-02 23:55
As a participant in the thread KHeilen linked to above I conducted an 'experiment' by setting MintUpdate to refresh at 1 day intervals and I can confirm, unsurprisingly, that on my machine when MintUpdate is set to 'refresh' at an interval greater than daily uptime I do not get notified of available update/upgrades. Using Synaptic, when clicking reload before use, does refresh the package lists, of course, and MintUpdate then notifies of available updates/upgrades on next boot.

As a home user with no specialist computing knowledge (I will admit to an above average interest and desire to learn though) I find this behaviour contrary to Mint's user friendly approach. While every user has to rake responsibility for the health of their machine and apply upgrades sensibly, instead of blindly, this is difficult to do when the tool provided to deal with updates/upgrades can so easily be configured (without any warning) in such a way as to give a false sense of security and seemingly incorrect information.

Regards
WT

**Comment by gritty-gitty** [comment] 2015-04-18 17:09
@wintertroubles: You must not feel insecure at all because of that ;-). This is Linux, and if you don’t run a server accessible from the Internet, you won’t ever be in trouble if you forget a so-called “security update”. As Clem [pointed it out long ago](http://forums.linuxmint.com/viewtopic.php?f=47&t=103740#p602140), the purpose of *mintUpdate* is not exactly to keep you safe, but to give you an *easy way to upgrade* if you wish to — not the way Windows, MacOS X, or even Ubuntu do.

That being said, even the fact of letting your machine run longer than a day won’t guarantee that *mintUpdate* will catch pending updates. As far as I’m concerned, I *do* let run my computer continuously with the refresh period set to a few days, but that doesn’t keep me from having missed them for a while: there is currently that nasty issue of [cinnamon freezing every now and then](https://github.com/linuxmint/Cinnamon/issues/2946), hence I’m forced to log out quite often, so there is no chance to hit the refresh time, all the more because I don’t want to have to update too frequently.

Thus, the only solution is to catch new updates by a cron job that downloads the package list all by itself, independently from *mintUpdate*. You can for example use the script from the tutorial [Auto Updating the Package List for the Update Manager](http://community.linuxmint.com/tutorial/view/1347). If a daily interval is too short for you, you can install it into /etc/cron.weekly as an alternative.

**Comment by wintertroubles** [comment] 2015-04-18 17:33
@gritty-gitty I don't feel insecure :-) I personally do feel that some updates/upgrades are important for the average home user, such as browser and flashplayer, but I agree that a small delay in receiving the upgrade is rarely catastrophic. However, as the post  on Mint Forums linked to by KHeilen above shows, there are users that have inadvertently set their system in such a way as to not query the repos.. as this is unlikely to be by design my above post was simply a confirmation of the original bug report by KHeilen.

Regards
WT

**Comment by gritty-gitty** [comment] 2015-06-03 22:15
For me, *mintUpdate* v4.8.4 is **always** failing to query the repositories after having checked the local package list on startup. It writes “Auto-refresh timer is going to sleep for …”, etc. to the logs — and that’s it, it never gets awoke again.

So I decided to restart it periodically with a *crontab* entry, in addition to the update of the package list by *apt-get* in the background.

**Comment by xenopeek** [comment] 2018-01-25 20:32
This issue appears to have been overlooked for closing. It was fixed with Linux Mint 18.

**Closed by xenopeek** 2018-01-25 20:32 UTC
Labels: FEATURE REQUEST
