### ISSUE TITLE
What changed in my updated package?

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/mintupdate#484] opened 2019-03-10 11:02 UTC
---
name: browse mintupdate changelogs history
about: accessing changelog for previously updated packages
title: 'What changed in my updated package?'
labels: FEATURE REQUEST
assignees: ''

---

**Is your feature request related to a problem? Please describe.**
As a mintupdate User I expect a easy way to get the changelog for a package I just updated. Now it's quite hard and involves many steps and starting other applications, or is there something I'm missing?

**Describe the solution you'd like**
- As a mintupdate User I open mintupdate and in menu View -> History of updates, I click on the package I want to investigate in the list, and the desired changelog if existing is shown, else I get informed that there is no changelog found. Right now History of updates doesn’t feel very useful and needs to be more interactive?
- A good simple browsing function, like gnome-logs would be nice, for browsing sources types mint, debian, ubuntu, ppa, all etc.
- Minimum and one idea would be to open the chosen package changelog in the default web browser if changelog is online or is opening local changelog.gz perhaps better? A bit rough but still good enough?

**Describe alternatives you've considered**
- Using apt-listchanges and checking /usr/share/doc/packagename/changelog.gz or changelog.Debian.gz involve some manual digging or custom scripting. Or is there some good stuff out there or other solution that I’m not aware of?
- Checked Synaptic but it's too many clicks and jumping around, I really like mintupdate :)

**Additional context**
Add any other context or screenshots/illustrations about the feature request here.
- My current version of mintupdate is 5.4.7 at the moment I’m in LM 19.1 64bit / Cinnamon 4.0.9

**Comment by gm10** [comment] 2019-03-10 13:40
Duplicate of #283, see referenced patch there.

**Closed by gm10** 2019-03-10 13:40 UTC
Labels: FEATURE REQUEST

**Comment by jorgenqv** [comment] 2019-03-10 14:01
@gm10 ok thanks!
