### ISSUE TITLE
mintupdate does not show in tray and does not start

### ISSUE THREAD

**Issue by timmie** [linuxmint/mintupdate#88] opened 2015-02-22 13:33 UTC
The programme does not show in tray anymore and on console I get this:
```
$: mintupdate-launcher 

(mintUpdate.py:29006): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:29006): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:29006): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:29006): libglade-WARNING **: unknown attribute `swapped' for <signal>.
Attempt to unlock mutex that was not locked
Aborted (core dumped)
```
and
```
$:mintupdate
(mintUpdate.py:4906): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:4906): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:4906): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:4906): libglade-WARNING **: unknown attribute `swapped' for <signal>.
Attempt to unlock mutex that was not locked


```

Using:
lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 17.1 Rebecca
Release:	17.1
Codename:	rebecca

dpkg -l|grep cinnamon
ii  cinnamon                                                    2.4.6-20150222040005-trusty                         amd64        Cinnamon desktop

 dpkg -l|grep mintupdate
ii  mintupdate                                                  4.8.1                                               all          Update Manager

**Comment by monsta** [comment] 2015-02-27 09:11
duplicate of https://github.com/linuxmint/mintupdate/issues/86
also see https://github.com/linuxmint/mintinstall/issues/82#issuecomment-73022841

**Closed** 2015-02-27 13:23 UTC
