### ISSUE TITLE
Character Problem On Linux Kernel Description

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintupdate#239] opened 2017-05-19 18:37 UTC
Hi,

There is Linux Kernel description character problem at Mintupdate.

Could you look following image.

![mintupdate-tr](https://cloud.githubusercontent.com/assets/1300133/26261852/7af1aa24-3cdb-11e7-8965-54e01eb3d7ad.png)

**Comment by xenopeek** [comment] 2018-01-25 23:04
Duplicate of #230. Fixed.

**Closed by xenopeek** 2018-01-25 23:04 UTC
