### ISSUE TITLE
Mintupdate : keyboard shorcuts for updatemanager not working !

### ISSUE THREAD

**Issue by jinvoker** [linuxmint/mintupdate#393] opened 2018-10-01 09:11 UTC
Using linuxmint 19 -Tara 64 cinnamon

The keyboard shortcuts for mintupdate 5.4.1 not working as expected . Looking into the issue would give ease of access n faster deployment of updates.

**Comment by icarter09** [comment] 2018-10-11 03:38
Linux Mint 19 64bit
Cinnamon 3.8.9

Verified this issue. Looks like the only shortcut that does work is 'Ctrl + W', which closes the Update Manager. 

@jinvoker I'm debugging the issue. Thanks for the heads up.

**Comment by chingyinwan123** [comment] 2018-10-11 07:11
May I assist with this issue?

**Comment by chingyinwan123** [comment] 2018-10-11 08:18
I have a fix for this issue ready. Should I make a pull request?

**Comment by jinvoker** [comment] 2018-10-11 08:33
So glad the issue is taken up pretty fast. I needed to notify because as the issue may be simple, it's one of the commonly used apps that needed a fix .

**Comment by icarter09** [comment] 2018-10-11 11:42
@chingyinwan123 thank you! In the future, you don't have to wait for anyone to ask or tell anyone if you want to work on an issue. If you have a PR for an issue, go ahead and push it so others can verify the fix. The sooner the issue is fixed, it's a win for everyone. Good job on the quick turn around.

**Closed** 2018-10-25 21:21 UTC
Labels: In Progress
