### ISSUE TITLE
[Cinnamon & Mate] If you manually open Update Manager right after login within 20 seconds, the window will automatically close

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mintupdate#730] opened 2022-04-08 20:41 UTC
This is basically just the issue described in the following thread:
- https://forums.linuxmint.com/viewtopic.php?f=90&t=371476

Basically on both 20.3 Mate and LMDE5, whether fresh installs or fully-updated installs, right after login, if you manually open the Update Manager within 20 seconds (whether via the Applications menu or via an existing shortcut you manually created), the Update Manager's program window will then automatically close on its own 20 seconds after the time you had logged in.

I don't actually know if it's exactly 20 seconds, but it seems to coincide with the configuration in "Startup Applications" for the Update Manager (which is set to 20 seconds by default for the Update Manager).

This issue doesn't occur on 20.3 XFCE since that version of Mint doesn't seem to support delayed launching of startup appliations and instead just automatically launches the Update Manager immediately after login (I tried my best to manually launch the Update Manager before it gets automatically launched to see if the issue does actually occur, but I just never could make it happen even when pinning a shortcut to it on the panel in the very bottom-right corner of my screen)

Also I did not test it on 20.3 Cinnamon since I figured that it occurring in LMDE5 and 20.3 Mate pointed to it not being something inherent to the desktop environment nor to whether it was based on Ubuntu or Debian.

**Comment by xenopeek** [comment] 2022-04-09 06:31
Duplicate of #604.

The auto-start is by design and there can be only one mintupdate process running at a time, hence the killing of the other process. If you want to manually start mintupdate you can disable the auto-start in Startup Applications.

**Closed by xenopeek** 2022-04-09 06:31 UTC
Labels: BUG

**Comment by NintendoManiac64** [comment] 2022-04-09 07:11
Just to clarify, is it intentional that the new process doesn't re-open the window if the window was open (and not just the process was open)?

**Comment by xenopeek** [comment] 2022-04-09 09:20
Yes, the entry in Startup Applications updates your spices and flatpaks (if enabled in Update Manager) so the Update Manager window already open could be showing outdated information if it wasn't restarted.

**Comment by NintendoManiac64** [comment] 2022-04-09 19:02
So I'm guessing this means that smurphos's following suggestion posted on the forum is a non-starter?

"It could check for another running process and kill itself rather than the other existing process. Would be a better design...."

Nevertheless, currently when it's automatically restarted, it doesn't re-launch the program window if the program window was already open...

**Comment by xenopeek** [comment] 2022-04-10 04:17
Yes as per my understanding that is a non-starter. It's not a better design because the existing process could be showing outdated information.

You can tweak the startup delay in Startup Applications if you must or you can disable it from Startup Applications (no more automatic updates) if you want to manually start it. I guess the startup delay is to spread out the load from all the processes that are loaded after log in.

I guess for most users they log in, start the programs they need their computer for and at some point during the day spot that Update Manager icon shows there are updates and apply them at a convenient time. Not the first thing they do in the day. Why is the 20 seconds startup delay a problem for you?
