### ISSUE TITLE
Kernels window under update manager shows wrong info if the installed kernel is low-latency

### ISSUE THREAD

**Issue by minto0s** [linuxmint/mintupdate#335] opened 2018-04-02 20:19 UTC
I routinely (manually) install kernels from ubuntu's kernal repository in my LM18.3 system. 
When the two header files and the single image file are installed the newly installed kernel is referenced in the kernel window under update manager, EXCEPT if the kernel is low latency, in which case the kernel window ignores it and doesn't show it in the list at all. 

This in my view is a bug to begin with, because if the kernel is a -generic type it properly shows up even though it is not provided by the LM kernel repos. 

Of course, one might argue that this is a feature, - not a bug - because maybe LM doesn't support low latency kernels or any kernel not sourced from its own repo, AND the fact that -generic type kernels show up properly is due to pure good luck...

But then, why would it say "You are currently using the kernel:" followed by the wrong kernel info? 

Either it should identify the right kernel, or simply be silent if the kernel is not supported or not dealt with.

In my opinion this is a second bug closely related to the first one, or with the earlier remark a bug in its own right.

This anomaly relates to mintUpdate 5.3.2.1. By the way the messages are slightly different between amd64 and i386, but the errors the same.

To replicate the problem on either amd64 or i386 system, simply install ubuntu kernel 4.15.15 low latency using the dpkg -i of its 3 .deb files. Reboot the machine into the new kernel and verify it with uname -a

Next go to update manager's kernel window and you'll see that it says "Kernel 3.13.0-37-generic currently loaded" whereas actually 4.15.15 low latency is loaded (and 3.13 is not even installed let alone loaded).

Thanks for your attention.

PS: After posting the above material I noticed that there was an issue opened quite some time ago about the same problem but with a different narrative. I think my input has the merit of bringing this issue up to date, so I am not deleting it. 
In another post I am also suggesting that provision be made to allow simultaneous installation of generic and low latency versions of a given kernel version.

**Comment by xenopeek** [comment] 2018-04-05 09:59
Closing this as duplicate of #200. You've done more thorough analysis before reporting but discussion is ongoing on the other issue. Let's continue there.

**Closed by xenopeek** 2018-04-05 09:59 UTC
