### ISSUE TITLE
"Restart to apply the updates" even when you update a kernel that is not active at the moment

### ISSUE THREAD

**Issue by costagabbie** [linuxmint/mintupdate#728] opened 2022-03-30 15:37 UTC
**Describe the bug**
Once you update a kernel package this message will show up, even if the kernel package that got update is not the active kernel at the moment, for example if i have a 5.13.X and it is the active kernel at the moment but there is a update for 5.4.X, once the mintupdate finishes updating 5.4.X it will display the panel with a message about rebooting to apply the updates.

**Screenshots**
If applicable, add screenshots to help explain your problem, you can just drag & drop them here.

**To Reproduce**
1. Have two kernel 'lines' installed
2. Boot from one kernel 
3. Update the other kernel
4. mintupdate will ask you to restart your computer to apply the update of a inactive kernel. 

**Expected behavior**
Mint update show this message only when the active kernel line is updated, if im booted on 5.13 and there is a 5.13 update it should show the message, if im on 5.13 and 5.4 updates it should not since it has the potential of confusing inexperienced users.

**Distribution:**
- [X] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)

**Software version:**
5.8.1

**Logs:**
Copy & paste the log output from Update Manager > View > Information here.

**Crash report:**
Not Applicable

**Comment by LinuxOnTheDesktop** [comment] 2022-11-11 13:38
This issue is a duplicate of #645.

I am glad to see that @costagabbie has created a fix for the problem!

**Comment by LinuxOnTheDesktop** [comment] 2023-01-07 00:34
This problem persists in Mint Vera. I suppose I'll have to try implementing costagabbie's fix. (Also: @costagabbie: thank you for your work; how about submitting a pull request to Mint?)

**Comment by costagabbie** [comment] 2023-01-09 22:16
@LinuxOnTheDesktop the fix is about 2 lines, if any of the developers are interested in fixing this bug they can easily read this issue and implement the fix in 1 minute and push it.

**Comment by LinuxOnTheDesktop** [comment] 2023-01-09 22:35
@costagabbie : yes, but it's a fact of life around here that a fix is more liable to arise if there is a pull request for it. So, I'll make a PR (crediting you) once I get around to it. (I know that making that PR is trivial but it is not trivial _for me_, because my git skills are very rudimentary.)

**Comment by costagabbie** [comment] 2023-01-10 12:27
> @costagabbie : yes, but it's a fact of life around here that a fix is more liable to arise if there is a pull request for it. So, I'll make a PR (crediting you) once I get around to it. (I know that making that PR is trivial but it is not trivial _for me_, because my git skills are very rudimentary.)

don't worry i already made the pull request for it.
now we wait for the developers to notice.

**Comment by clefebvre** [comment] 2023-05-08 14:28
Duplicate of https://github.com/linuxmint/mintupdate/issues/645.

**Closed by clefebvre** 2023-05-08 14:28 UTC
Labels: BUG
