### ISSUE TITLE
Update manager closes if opened right after boot up 

### ISSUE THREAD

**Issue by QazPolma** [linuxmint/mintupdate#559] opened 2019-08-02 09:53 UTC
**Describe the bug**
If I open the update manager as soon as the computer starts up, the manager will close before I manage to run refresh + update. 
There seems to be ~20 second timeout and if I time it incorrectly, the window will close as soon as it opens.

**To Reproduce**
Start "Update Manager" as soon as computer boots up and wait ~20 seconds.

**Expected behavior**
Update manager doesn't close for no apparent reason.

**Distribution**
Linux Mint Cinnamon 19.1 

**Software version**
5.4.7

**Comment by xenopeek** [comment] 2020-05-24 09:55
Duplicate of #604

mintupdate is automatically started 20 seconds after you log in and when you start mintupdate manually before that, your mintupdate gets killed because each time mintupdate is started it kills any other running mintupdate. I assume that's the case for you. As a workaround you can disable Update Manager in Startup Applications for that account, to disable it starting automatically.

**Closed by xenopeek** 2020-05-24 09:55 UTC
