### ISSUE TITLE
Request: Don't close kernel window automatically

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/mintupdate#225] opened 2017-03-27 18:59 UTC
...or at least provide a checkbox to let the window stay open.

Reason: I often install two new kernels, e.g. 4.4.0-70 and 4.8.0-44, and remove two or more older ones.
For this I have to open the window a few times, that's unnecessary.
I am tempted to use synaptic for this action, but the Mint kernel window is much more clear,

**Comment by calexil** [comment] 2017-05-08 20:53
@clefebvre Feature request

**Comment by NikoKrause** [comment] 2017-06-18 17:20
That's a duplicate of https://github.com/linuxmint/mintupdate/issues/130

**Closed** 2017-06-18 17:24 UTC
