### ISSUE TITLE
Hardcoded Tray Icons

### ISSUE THREAD

**Issue by Foggalong** [linuxmint/mintupdate#133] opened 2016-01-25 11:34 UTC
The icons displayed in the tray shouldn't be hardcoded. They look horribly out of place when a theme is used.

**Comment by EduardDopler** [comment] 2016-01-25 11:37
Possible duplicate of #101.

Actually, they aren't hardcoded as one can change them easily. But currently they aren't themeable. Please also note my Pull Request #132.

**Comment by Foggalong** [comment] 2016-01-25 11:43
That's a different issue by the looks of things. It just wants to make the icons symbolic so that they recolour according to the theme used, this is about un-hardcoding the icons so they can be completely replaced by the users chosen icon theme.

**Comment by EduardDopler** [comment] 2016-01-25 11:46
But they can be changed by the user already.
Also, they aren't (m)any icon themes with default icons for all states MintUpdate needs.

**Comment by Foggalong** [comment] 2016-01-25 12:03
I can think of at least 3 off the top of my head, one being [Numix](https://github.com/numixproject/numix-icon-theme) which I develop. The reason I filed this issue is because we've had our users coming to us saying they want Numix icons for Mint Update, but we can't ship them with our themes because they're hardcoded on this side.

They can be changed by the user sure, but they should be changed by icon themes as per free desktop standards.

**Comment by EduardDopler** [comment] 2016-01-25 12:16
You are right.
The application should look in the icon theme's folder and only fallback to its default icons if the theme doesn't ship with such icons.

**Comment by Foggalong** [comment] 2016-01-25 12:18
:+1: that's a different issue to #101 right? correct me if I've understood how the solution there works

**Comment by EduardDopler** [comment] 2016-01-25 12:41
Yes, it is different because the solution there depends on icons in a non-default Free Desktop folder. It *does* change it's color based on the status bar's main color (e.g. light color if the theme is dark, dark color otherwise). Also, the icon can be changed by the user. **But** changing the global icon theme does not change the icon itself (i.e.the style/appearance rather just the color).

**Comment by Foggalong** [comment] 2016-01-25 17:27
Cool :+1:

**Comment by EduardDopler** [comment] 2016-01-25 18:18
I'd like to change that at least for my version. It seems that you're familiar with these things; so what's the convention, where do the icons have to be located for such support?

**Comment by Foggalong** [comment] 2016-01-25 18:54
They have to be in `/usr/share/icons/hicolor/` or `~/.local/share/icons/hicolor/` depending if you want them available system wide or not. Within there they go into their respective size directory (like `22x22/` for 22px icons) and then the type of icons directory (in this case `status/`).

**Comment by EduardDopler** [comment] 2016-01-26 09:10
I was thinking to implement it the following way:
- The script looks for icons in both locations you mentioned (`~/.local/…` first, then `/usr/…`) for files called `mintupdate-$status`.
- The script installs it default icons as `/usr/share/icons/hicolor/scalable/mintupdate-$status-symbolic.svg`. These icons are symbolic, i.e. they change color according to the theme (dark/light). Plus, it creates a symlink named `mintupdate-$status.svg` to these symbolic icons.

So if no theme with custom mintUpdate icons is present, it tries `mintupdate-$status.svg`, gets redirected to `mintupdate-$status-symbolic.svg` and thus provides the default indicator icon which honors the theme color.

Would that be favorable?

**Comment by JosephMcc** [comment] 2016-01-26 10:39
The issue with making them symbolic is that not all distros support symbolic icons on the panel. In Mate, for example, I think you have to use full color versions.

**Comment by EduardDopler** [comment] 2016-01-26 11:26
@JosephMcc 
Maybe I'm wrong but I thougt that the only difference in symbolic and non-symbolic icons is that symbolic icons lead to their fill color `#bebebeff`being replaced depending on whether a dark or a light theme is active.
So, why isn't Mate capable of just displaying such icons?

**Comment by JosephMcc** [comment] 2016-01-26 12:01
Well the color is controlled by the gtk theme. But it has to be supported. I'm not sure if they even work properly in gtk2 and need to be supported regardless. From a few issues I've seen closed on the Mate github pages I'm not sure they have any plans to support these on the panel any time soon. Likely xfce doesn't support them either, though I don't actually know.

**Comment by Foggalong** [comment] 2016-01-26 12:16
@JosephMcc XFCE has supported them for yonks now, so it surprises me that MATE doesn't given that its development moves much quicker. Though even if `-symbolic` isn't supported by MATE it's possible to use monochrome `22x22/status` icons (like @EduardDopler said) since they work just like normal icons, and would have far better consistency than the full colour variants.

@EduardDopler There's an actual GTK icon lookup function for implementing that first point. It's a bit more complicated than that since you have to look at the applied icon theme and then move down the inherits tree looking for the icons. I'm not a GTK developer myself so I couldn't tell you what the function is off hand, I just know it exists.

**Comment by EduardDopler** [comment] 2016-01-28 10:31
@Foggalong Since mintupdate is likely to undergo major restructuring in the near future—at least that's what I got from the IRC channel—I stop working on it here. I wasn't able to get the directions this project will go. Also, it seemed to me that no external dev's opinion is needed on this topic. Wish you luck though!

**Comment by JosephMcc** [comment] 2016-03-08 21:33
Submitted a PR here which moves all mintupdate icons to the hicolor theme so third party themes can properly theme them.

**Comment by JosephMcc** [comment] 2016-03-10 20:42
This is now fixed. All the mintupdate icons should be properly themeable.

**Closed by JosephMcc** 2016-03-10 20:42 UTC

**Comment by Foggalong** [comment] 2016-03-13 18:43
Do we know what icon names are being used?

**Comment by JosephMcc** [comment] 2016-03-13 20:47
@Foggalong here: https://github.com/linuxmint/mintupdate/tree/master/usr/share/icons/hicolor/48x48/status

This will be included in the Linux Mint 18 release so it doesn't effect users of Mint 17.
